# Generated by Django 4.0.4 on 2022-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
